### ISSUE TITLE
!fixme

### ISSUE THREAD

**Issue by Fermoder** [foogs/FoogsProjects#28]
Фикс игрока (пустой космос и т.д.), ситуации когда у человека 2 тела, застрял без возможности самоубийства и прочее.
Выполнение:
1. Написать команду.
2. Выкидывает с сервера.
3. Удаляет всех персонажей написавшего игрока.
3.1. На всякий случай выкидывает всех персонажей из всех гридов автора команды (если можно).

**Comment by foogs** [comment]
Можно

пн, 16 сент. 2019 г., 15:29 Fermoder <notifications@github.com>:
