### ISSUE TITLE
Problems with setting up Rewards plugin

### ISSUE THREAD

**Issue by BartasRS** [foogs/FoogsProjects#31]
Cannot enter any values, every field and button is disabled. I run torch on GTX server so I installed blank server on my local machine to set up configs and copy those to the server but this one plugin is just not working. Can I have example cfg file with a place to enter server API key? CFG file generated after installing this plugin does not have it.

**Comment by foogs** [comment]
Install blank server on local machine and set up configs and copy to the server. 
 This way works perfectly.
