### ISSUE TITLE
Rewards не работает. SE 1.199

### ISSUE THREAD

**Issue by Sigurdovich** [foogs/FoogsProjects#33]
После выхода обновления SE 1.199 перестал работать плагин - выдаёт только KeenVirtualCash. При этом команда !reward отрабатывает без ограничения, хоть 100500 раз подряд получай награду

**Comment by foogs** [comment]
https://torchapi.net/plugins/item/8d5546e1-586d-4cdd-9823-2425291fc7d5 последняя версия работает =)
